---
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport-svc
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: http-web
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: kprom
    app.kubernetes.io/name: grafana
  sessionAffinity: None
